# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14FLAGS=-O3" >> ~/.R/Makevars
  - echo "CXX11FLAGS=-O3" >> ~/.R/Makevars
  - echo "CXX14 = g++ -std=c++1y" >> ~/.R/Makevars
