# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
language: r
sudo: false

# added lines to install rstan on travis 
# source: https://github.com/dmenne/breathteststan/blob/master/.travis.yml

# matrix:
  # include:
    # - os: linux
      # addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
          # packages:
            # - g++-7
      # env:
        # - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
  - chmod +x ./configure
  - chmod +x ./cleanup
  - mkdir -p ~/.r/
  - echo "cxx14 = g++-7 -fpic -flto=2" >> ~/.r/makevars
  - echo "cxx14flags = -mtune=native -march=native -wno-unused-variable -wno-unused-function -wno-unused-local-typedefs -wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

#r:
#  - release
#  - oldrel

#os:
#  - linux
#  - osx
#  - windows

# osx_image: xcode7.3

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
  - rstan
  - RcppArmadillo
  - testthat
  
# install:
  # - R -e "install.packages('rstan')"
  # - R -e "install.packages('Rcpp')"
  # - R -e "install.packages('RcppArmadillo')"
  # - R -e "install.packages('testthat')"

# added to run configure script for OpenMP problems on macOS & clang
# compiler:
  # - clang
  # - gcc

# before_script:
  # - ./configure