# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# added lines to install rstan on travis 
# source: https://github.com/dmenne/breathteststan/blob/master/.travis.yml

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX1X=g++-7" >> ~/.R/Makevars
  - echo "CXX1XSTD=-std=c++11" >> ~/.R/Makevars
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars
  

# added to run configure script for OpenMP problems on macOS & clang
# compiler:
  # - clang
  # - gcc

# before_script:
  # - ./configure